version: '3.8'

services:
  
  db:
    image: postgres:16
    container_name: payroll-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sekyurpayroll!  
      POSTGRES_DB: sekyurlink_payroll
    
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - payroll_network

  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payroll-api
    restart: always
    ports:
      - "5016:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production 
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=sekyurlink_payroll;User Id=postgres;Password=sekyurpayroll!;
      - EmailSettings__AppPassword=gjboiqiuruectfza 
    networks:
      - payroll_network


networks:
  payroll_network:
    driver: bridge

volumes:
  pgdata: